### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by elssam** [ikmb/gwas-qc#3]
Hi,

I got the following error while running the pipeline for the test dataset. Please advise on how to overcome this issue. Thanks a lot.

Samar

````
Error executing process > 'batch_statistics (Example/1000G_controls)'
  
  Caused by:
    Failed to pull singularity image
    command: singularity pull  --name jkaessens-ikmb-gwas-qc-assoc-assets.sif library://jkaessens/ikmb-gwas/qc-assoc-assets.sif > /dev/null
    status : 255
    message:
      [33mWARNING: No default remote in use, falling back to: https://library.sylabs.io
      FATAL:   While pulling library image: image jkaessens/ikmb-gwas/qc-assoc-assets.sif:latest (amd64) does not exist in the library
```

**Comment by jkaessens** [comment]
Hi,

thanks for reporting. We had an issue with the library provider, that should be fixed now. Please try again.

**Comment by cemmeydan** [comment]
Hi,
We are still encountering this issue. Is there a work-around to download the container?

```
singularity pull  --name jkaessens-ikmb-gwas-qc-assoc-assets.sif library://jkaessens/ikmb-gwas/qc-assoc-assets.sif
FATAL:   While pulling library image: image jkaessens/ikmb-gwas/qc-assoc-assets.sif:latest (amd64) does not exist in the library
```

**Comment by lwienbrandt** [comment]
Hi cemmeydan,
sorry, that it took us so long to find a way to solve the issue. We encountered the same problem again with oour library hoster, but as a workaround you can download the container now from one of our servers.
Please follow the instructions in the updated Readme. (Note that the name of the container has changed slightly.)
Thank you and sorry for the inconvenience.
Lars

**Comment by cemmeydan** [comment]
Thank you, it is working with the new image.
